name-template: $NEXT_MINOR_VERSION
tag-template: $NEXT_MINOR_VERSION
categories:
  - title: ⬆️ Dependencies
    label: dependencies
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'dependencies'
      - 'chore'
      - 'fix'
  default: patch

template: |
  ## Changes
  $CHANGES