site_name: aiomusiccast
site_description: Companion library for musiccast devices intended for the Home Assistant integration.
site_author: Tom Schneider

repo_url: https://github.com/vigonotion/aiomusiccast
edit_uri: https://github.com/vigonotion/aiomusiccast/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
